services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: wishlist
      POSTGRES_USER: wishlist
      POSTGRES_PASSWORD: P@ssw0rd
